name: 📄 Prompty – walidacja i styl

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  markdown-validation:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout repo
      uses: actions/checkout@v3

    - name: 🐍 Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 📦 Install dependencies
      run: |
        pip install markdown

    - name: ✅ Walidacja plików Markdown
      run: |
        find ./GPT-Prompty/prompt_templates -name "*.md" -exec python -m markdown {} \;

    - name: 🔍 Sprawdzenie nagłówków
      run: |
        for f in GPT-Prompty/prompt_templates/*.md; do
          grep -q "^# " "$f" || (echo "$f: brak nagłówka '#'" && exit 1)
        done
